### ISSUE TITLE
POSIX Awk as a target

### ISSUE THREAD

**Issue by pdietl** [cotowali/cotowali#137]
Perhaps it would be interesting to try to target AWK as an output. It's functions are not run in sub shells and it can do all math itself. I am thinking of this because of how horridly slow sh is at doing the raytracing example since it spends almost all its time calling other programs. AWK also has better array support. 

Would you be interested if I attempted to contribute this?

**Comment by zakuro9715** [comment]
I have thought about the awk backend. It is an attractive option and has been put off simply because of the cost of implementation, so contributions are most welcome!

Contributors are appreciated and will help as much as possible. If you have any questions with development, please ask any questions on discord(https://discord.com/invite/nwEad5dNYg).  

Note:  We will do  large refactoring. This will last for several months; please note that the AST structure, etc. will change frequently.

**Comment by pdietl** [comment]
Hi @zakuro9715. Have you completed your large refactoring? Is the AST structure more stable now?
